apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbmaofs
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbmaofs/veilarbmaofs:{{version}}
  port: 80
  liveness:
    path: /isAlive
    initialDelay: 15
  readiness:
    path: /isReady
    initialDelay: 15
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 1Gi
  ingresses:
    - https://veilarbmaofs-q1.nais.preprod.local
    - https://app.dev.adeo.no/veilarbmaofs
    - https://app-q1.dev.adeo.no/veilarbmaofs
    - https://app-q1.adeo.no/veilarbmaofs
